<?php
    require '../dbconnect.php';
    session_start();
    $employee = $_SESSION['user_name'];
    $bill_id = $_POST['bill_id'];
    $bill_status = $_POST['bill_status'];
    $action = $_POST['action'];
    $bill_value = $_POST['bill_value'];
    $user_id = $_POST['user_id'];
    $cur_date = date('Y-m-d');
    $get_curr_status = "SELECT * FROM bill_fashionshop WHERE bill_id = '$bill_id'";
    $data_bill_status = mysqli_query($connect,$get_curr_status);
    $curr_status = '';
    if($data_bill_status){
        while($row = mysqli_fetch_assoc($data_bill_status)){
            $curr_status = $row['bill_status'];
        }
    }
    $get_fcm_token = "SELECT * FROM fcm_token_fashionshop WHERE user_id = '$user_id'";
    $arr_token = array();
    $data_fcm_token = mysqli_query($connect,$get_fcm_token);
    if($data_fcm_token){
        while($row = mysqli_fetch_assoc($data_fcm_token)){
            array_push($arr_token,$row['token']);
        }
    }
    function notify($to,$data){
        $api_key = "AAAAMroxAPU:APA91bEm-tD5lUfaAisjGNPYUHNiFJc-gnMy0XLexx5b9advsIyrr5Qft0sMxf8qgVpTDg5efse4dnLI0GvX1raidKlaBcXGWAtMsa0426eDsbisCfIbWnjxLd2Xwxmwu8O7ufwCvyOo";
        $url = "https://fcm.googleapis.com/fcm/send";
        $fields = json_encode(array('to'=>$to,'notification'=>$data));
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, ($fields));

        $headers = array();
        $headers[] = 'Authorization: key ='.$api_key;
        $headers[] = 'Content-Type: application/json';
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }else{
            
        }
        curl_close($ch);
    };
    if($curr_status == 'Đã giao'){
        switch ($action) {
            case 'Duyệt đơn':
                echo '<script type="text/JavaScript"> 
                alert("Đơn hàng đã được giao");
                history.back()
                </script>';
                break;
            case 'Chuyển sang đã giao':
                echo '<script type="text/JavaScript"> 
                alert("Đơn hàng đã được giao");
                history.back()
                </script>';
                break;
            case 'Hủy đơn':
                echo '<script type="text/JavaScript"> 
                alert("Đơn hàng đã giao không thể đổi trạng thái");
                history.back()
                </script>';
                break;            
            default:
                break;
        }
    }
    if($curr_status == 'Đã hủy'){
        switch ($action) {
            case 'Duyệt đơn':
                echo '<script type="text/JavaScript"> 
                alert("Không thể thay đổi trạng thái đơn hàng đã hủy");
                history.back()
                </script>';
                break;
            case 'Chuyển sang đã giao':
                echo '<script type="text/JavaScript"> 
                alert("Không thể thay đổi trạng thái đơn hàng đã hủy");
                history.back()
                </script>';
                break;
            case 'Hủy đơn':
                echo '<script type="text/JavaScript"> 
                alert("Không thể thay đổi trạng thái đơn hàng đã hủy");
                history.back()
                </script>';
                break;            
            default:
                break;
        }
    }
    if($curr_status == 'Chờ duyệt'){
        switch ($action) {
            case 'Duyệt đơn':
                $confirm_bill = "UPDATE bill_fashionshop SET bill_status = 'Đang giao', employee = '$employee' WHERE bill_id = '$bill_id'";
                mysqli_query($connect,$confirm_bill);
                //check remain product
                $get_bill_quantity = "SELECT * FROM detail_bill_fashionshop INNER JOIN product_size_fashionshop ON detail_bill_fashionshop.product_size_id = product_size_fashionshop.product_size_id INNER JOIN products_fashionshop ON detail_bill_fashionshop.product_id = products_fashionshop.product_id WHERE detail_bill_fashionshop.bill_id = '$bill_id'";
                $product_sold_out = '';
                $data_bill_quantity = mysqli_query($connect,$get_bill_quantity);
                if($data_bill_quantity){
                    while($row = mysqli_fetch_assoc($data_bill_quantity)){
                        if($row['quantity']>$row['remain_product'] || $row['status'] == 'Hết hàng'){
                            $product_sold_out = 'Sản phẩm không đủ trong kho hoặc đang ở trạng thái hết hàng, vui lòng kiểm tra lại trong kho hàng';
                        }
                    }
                }
                if(strlen($product_sold_out)>0){
                    echo '<script type="text/JavaScript"> 
                        alert("'.$product_sold_out.'");
                        history.back()
                        </script>';
                }else{
                    $update_product_quantity = "UPDATE product_size_fashionshop SET remain_product = remain_product - 1 
                    WHERE product_size_id IN (SELECT product_size_id FROM detail_bill_fashionshop WHERE bill_id = '$bill_id')";
                    $update_product_quantity_data = mysqli_query($connect,$update_product_quantity);
                    if($update_product_quantity_data){
                        $update_total_spend = "UPDATE user_fashionshop SET total_spend = total_spend + '$bill_value' WHERE user_id = '$user_id'";
                        mysqli_query($connect,$update_total_spend);
                        $data = array(
                            'title'=>'Đơn hàng '.$bill_id,
                            'body'=>'Đơn hàng của bạn đã được duyệt'
                        );
                        for($i = 0; $i<count($arr_token); $i++){
                            $to = $arr_token[$i];
                            notify($to,$data);
                        }
                        echo '<script type="text/JavaScript"> 
                        alert("Đơn hàng đã được duyệt");
                        history.back()
                        </script>';
                    }
                }
                break;
            case 'Chuyển sang đã giao':
                echo '<script type="text/JavaScript"> 
                alert("Đơn hàng chưa được duyệt");
                history.back()
                </script>';
                break;
            case 'Hủy đơn':
                $cancel_bill = "UPDATE bill_fashionshop SET bill_status = 'Đã hủy' WHERE bill_id = '$bill_id'";
                mysqli_query($connect,$cancel_bill);
                $data = array(
                    'title'=>'Đơn hàng '.$bill_id,
                    'body'=>'Đơn hàng của bạn đã bị hủy'
                );
                for($i = 0; $i<count($arr_token); $i++){
                    $to = $arr_token[$i];
                    notify($to,$data);
                }
                echo '<script type="text/JavaScript"> 
                alert("Đơn hàng đã được hủy");
                history.back()
                </script>';
                break;            
            default:
                break;
        }
    }
    if($curr_status == 'Đang giao'){
        switch ($action) {
            case 'Duyệt đơn':
                echo '<script type="text/JavaScript"> 
                alert("Không thể chuyển lại trạng thái duyệt đơn khi đang giao");
                history.back()
                </script>';
                break;
            case 'Chuyển sang đã giao':
                $cancel_bill = "UPDATE bill_fashionshop SET bill_status = 'Đã giao', date_shipped = '$cur_date' WHERE bill_id = '$bill_id'";
                mysqli_query($connect,$cancel_bill);
                $data = array(
                    'title'=>'Đơn hàng '.$bill_id,
                    'body'=>'Đơn hàng của bạn đã được giao'
                );
                for($i = 0; $i<count($arr_token); $i++){
                    $to = $arr_token[$i];
                    notify($to,$data);
                }
                echo '<script type="text/JavaScript"> 
                alert("Đơn hàng đã được giao");
                history.back()
                </script>';
                break;
            case 'Hủy đơn':
                echo '<script type="text/JavaScript"> 
                alert("Đơn hàng không thể hủy khi đang giao");
                history.back()
                </script>';
                break;            
            default:
                break;
        }
    }
    if($curr_status == 'Chờ hủy'){
        switch ($action) {
            case 'Duyệt đơn':
                echo '<script type="text/JavaScript"> 
                alert("Không thể duyệt đơn hàng đang chờ hủy");
                history.back()
                </script>';
                break;
            case 'Chuyển sang đã giao':
                echo '<script type="text/JavaScript"> 
                alert("Không thể duyệt đơn hàng đang chờ hủy");
                history.back()
                </script>';
                break;
            case 'Hủy đơn':
                $cancel_bill = "UPDATE bill_fashionshop SET bill_status = 'Đã hủy' WHERE bill_id = '$bill_id'";
                mysqli_query($connect,$cancel_bill);
                $data = array(
                    'title'=>'Đơn hàng '.$bill_id,
                    'body'=>'Đơn hàng của bạn đã được hủy'
                );
                for($i = 0; $i<count($arr_token); $i++){
                    $to = $arr_token[$i];
                    notify($to,$data);
                }
                echo '<script type="text/JavaScript"> 
                alert("Đã hủy đơn hàng");
                history.back()
                </script>';
                break;            
            default:
                break;
        }
    }
?>