<?php
    function notify($to,$data){
        $api_key = "AAAAMroxAPU:APA91bEm-tD5lUfaAisjGNPYUHNiFJc-gnMy0XLexx5b9advsIyrr5Qft0sMxf8qgVpTDg5efse4dnLI0GvX1raidKlaBcXGWAtMsa0426eDsbisCfIbWnjxLd2Xwxmwu8O7ufwCvyOo";
        $url = "https://fcm.googleapis.com/fcm/send";
        $fields = json_encode(array('to'=>$to,'notification'=>$data));
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, ($fields));

        $headers = array();
        $headers[] = 'Authorization: key ='.$api_key;
        $headers[] = 'Content-Type: application/json';
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }else{
            echo 'Ok';
        }
        curl_close($ch);
    };
    $to = "eXyItGbyTUazDGawA8jhLq:APA91bGskgF_xCm2lMEEYJd74B--YYBOT3maH0hob6QFffm37lN4QKzlxqAjeRiHwd2Nz5ddfZ0oqOF71U41DVrnCIfNu9YG5su-4Arl_ls2JI-jgdZ59y34s00jukP5fflAV8Q9JzD8";
    $data = array(
        'title'=>'Hi',
        'body'=>'Blah'
    );
    notify($to,$data);
    echo "Notification sent"
?>